name: 97 - Check that package-lock.json was changed only if package.json was changed

on:
  workflow_dispatch:
  pull_request:
    paths: [frontend/**, .github/workflows/30-frontend-tests.yml]
  push:
    branches: [main]
    paths: [frontend/**, .github/workflows/30-frontend-tests.yml]


  
jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: package.json updated
        if: (contains(steps.changed-files.outputs.changed_files, 'frontend/package.json')
        run: |
          echo "package.json udpated"
      - name: package-lock.json updated
        if: (contains(steps.changed-files.outputs.changed_files, 'frontend/package-lock.json')
        run: |
          echo "package.json udpated"
      - name: Fail if only one
        if: (((contains(steps.changed-files.outputs.changed_files, 'frontend/package.json'))&&(!contains(steps.changed-files.outputs.changed_files, 'frontend/package-lock.json')))|| ((!contains(steps.changed-files.outputs.changed_files, 'frontend/package.json'))&&(contains(steps.changed-files.outputs.changed_files, 'frontend/package-lock.json'))))
        run: |
          exit 1
